/**
 * Core types for MarkdownX
 * Defines the data structures for documents, manifests, and filesystem operations
 */

/**
 * Manifest for version control and feature detection
 * Stored in .mdx/manifest.json
 */
export interface Manifest {
  /** Format version of the document structure */
  formatVersion: number;
  /** Minimum app version required to read this document */
  minReaderVersion: number;
  /** List of enabled features */
  features: string[];
  /** AI-related metadata for future extensions */
  aiMetadata?: {
    /** Model used for embeddings */
    embeddingModel?: string;
    /** Last time embeddings were indexed */
    lastIndexed?: string;
    /** Document tags/keywords generated by AI */
    tags?: string[];
  };
}

/**
 * Document state stored in Automerge
 * This is the CRDT document structure
 */
export interface DocState {
  /** Markdown content */
  content: string;
  /** Document version counter */
  version: number;
  /** Last modification timestamp */
  lastModified: number;
  /** Document title (optional, extracted from content) */
  title?: string;
}

/**
 * Result of manifest validation
 */
export type ManifestValidationResult = 'ok' | 'read-only' | 'blocked';

/**
 * FileSystemAdapter interface
 * Abstracts file system operations for cross-platform compatibility
 * Desktop uses Node.js fs, Mobile uses expo-file-system
 */
export interface FileSystemAdapter {
  /** Read file as binary */
  readFile(path: string): Promise<Uint8Array>;
  /** Write binary file */
  writeFile(path: string, data: Uint8Array): Promise<void>;
  /** Read file as UTF-8 text */
  readTextFile(path: string): Promise<string>;
  /** Write UTF-8 text file */
  writeTextFile(path: string, content: string): Promise<void>;
  /** Check if path exists */
  exists(path: string): Promise<boolean>;
  /** Create directory (recursive) */
  mkdir(path: string): Promise<void>;
  /** List directory contents */
  readdir(path: string): Promise<string[]>;
  /** Watch for file changes. Returns unwatch function */
  watch(path: string, callback: (event: 'change' | 'rename', filename: string) => void): () => void;
  /** Rename/move file (atomic operation) */
  rename(oldPath: string, newPath: string): Promise<void>;
  /** Delete file */
  unlink(path: string): Promise<void>;
  /** Get file stats */
  stat(path: string): Promise<{ isFile: boolean; isDirectory: boolean; size: number; mtime: number }>;
}

/**
 * Options for initializing a MarkdownX document
 */
export interface InitDocOptions {
  /** Initial content (default: empty string) */
  initialContent?: string;
  /** Document title */
  title?: string;
}

/**
 * Result of loading a document
 */
export interface LoadDocResult {
  /** The loaded document state */
  state: DocState;
  /** The manifest */
  manifest: Manifest;
  /** Validation result */
  validation: ManifestValidationResult;
}

/**
 * Asset information
 */
export interface AssetInfo {
  /** Original filename */
  originalName: string;
  /** SHA-256 hash of content */
  hash: string;
  /** Stored filename (hash + extension) */
  storedName: string;
  /** Relative path from document root */
  relativePath: string;
  /** File size in bytes */
  size: number;
  /** MIME type */
  mimeType: string;
}

/**
 * Bridge message types for WebView communication
 */
export type BridgeMessage =
  | { type: 'LOAD'; basePath: string }
  | { type: 'LOADED'; content: string; manifest: Manifest }
  | { type: 'SAVE'; content: string }
  | { type: 'SAVED' }
  | { type: 'UPLOAD_IMAGE'; id: string; data: ArrayBuffer; fileName: string }
  | { type: 'UPLOAD_IMAGE_RESULT'; id: string; path: string }
  | { type: 'UPLOAD_IMAGE_ERROR'; id: string; error: string }
  | { type: 'EXTERNAL_CHANGE'; content: string }
  | { type: 'ERROR'; message: string };

/**
 * Configuration for sync engine
 */
export interface SyncEngineConfig {
  /** Base path of the .mdx folder */
  basePath: string;
  /** FileSystem adapter instance */
  fsAdapter: FileSystemAdapter;
  /** Callback when external changes are detected */
  onExternalChange?: (content: string) => void;
  /** Enable auto-save debounce (ms, default: 1000) */
  autoSaveDelay?: number;
}
